### ISSUE TITLE
CopyFileA Failed Error

### ISSUE THREAD

**Issue by Summ1tSunshine** [NUL0x4C/AtomPePacker#11]
I receive the following error with any 64bit binary I try to pack. I have tried both the dll and exe with the same error. Any idea what is going on here?

C:\Users\Dev\PePacker.exe Loader.exe -d
[i] Reading " Loader.exe " ...
[i] 64-PE Input Detected ... [ SUPPORTED ]
[i] Generating Dll Output ...
[!] "CopyFileA" [ FAILED ]      3

**Comment by NUL0x4C** [comment]
are you compiling manually ?

**Comment by Summ1tSunshine** [comment]
I am yes. In visual studio 2022.

**Comment by NUL0x4C** [comment]
can u try with the release version

**Comment by Summ1tSunshine** [comment]
The compiled release seems to work. Any idea why I am getting the error with my compiled version?

**Comment by NUL0x4C** [comment]
the PePacker.exe file expect a folder named "Modules" that is under the same directory. "Modules" contains the pe packing stubs needed to generate the final output:
- `Modules\DllPP64Stub.dll`: is used when you request a dll output
- `Modules\H_PP64Stub.exe`: is the default stub used 
- `Modules\PP64Stub.exe`: is the hidden stub 

So in order for the "PePacker.exe" file to work it needs these files, under this directory.

**Comment by NUL0x4C** [comment]
It is possible that you don't have these files, and thus when PePacker.exe is searching for them, it is failing.

**Comment by Summ1tSunshine** [comment]
This appears to have fixed it. Thanks. Creating the modules folder fixed the issue.
